name: CI Build & Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test API with Maven
      working-directory: ./api/brasileirao-api
      run: mvn -B test 

  build-and-test-ios:
    needs: build-and-test-api
    runs-on: macos-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'

    - name: Build and Run Unit Tests for iOS App
      working-directory: ./ios-app
      
      run: |
        xcodebuild clean build test \
          -project Brasileirao/Brasileirao.xcodeproj \
          -scheme Brasileirao \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
          -skip-testing BrasileiraoUITests \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO